# fly.toml app configuration file generated for diplometr on 2026-05-18T11:42:18+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'diplometr'
primary_region = 'fra'

[build]

[env]
  PORT = '8080'

[[mounts]]
  source = 'diplometr_data'
  destination = '/data'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
